In [1]:
import pandas as pd
import numpy as np

df=pd.read_excel("Payment_transaction.xlsx") #read the excel
df.head(5) #first 5rows display

,transaction_id,customer_id,transaction date,transaction time,transaction_amount,payment_method,transaction_status,failure_reason,bank_name,city,device_type,customer_type
0,TXN001,CUST001,2026-07-01,10:30,2500,UPI,Success,NaN,HDFC Bank,Chennai,Android,Existing
1,TXN002,CUST002,01/07/2026,11.15 AM,"₹3,500",upi,SUCCESS,NaN,hdfc bank,chennai,android,existing
2,TXN003,CUST003,2026/07/02,14:20:10,INR 1200,Debit Card,Failed,Insufficient Balance,SBI,Bengaluru,iOS,New
3,TXN004,CUST004,02-07-2026,03:45 PM,"4,800",debit card,failed,insufficient balance,sbi,Bangalore,IOS,new
4,TXN005,CUST005,03-Jul-2026,09.10.30,7000,Credit Card,Pending,NaN,ICICI Bank,Mumbai,Web,Existing

In [3]:
df.info() #data details

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   transaction_id      51 non-null     object
 1   customer_id         50 non-null     object
 2   transaction date    50 non-null     object
 3   transaction time    50 non-null     object
 4   transaction_amount  51 non-null     object
 5   payment_method      50 non-null     object
 6   transaction_status  51 non-null     object
 7   failure_reason      17 non-null     object
 8   bank_name           50 non-null     object
 9   city                50 non-null     object
 10  device_type         51 non-null     object
 11  customer_type       51 non-null     object
dtypes: object(12)
memory usage: 4.9+ KB

In [4]:
df.describe(include="all") #describe the all datatype

,transaction_id,customer_id,transaction date,transaction time,transaction_amount,payment_method,transaction_status,failure_reason,bank_name,city,device_type,customer_type
count,51,50,50,50,51,50,51,17,50,50,51,51
unique,50,49,49,49,47,12,8,10,13,13,7,5
top,TXN015,CUST015,2026/07/08,12:05,2100,UPI,Success,Network Error,SBI,Chennai,Android,Existing
freq,2,2,2,2,3,13,14,3,8,8,16,23

In [5]:
df.columns=(df.columns.str.strip().str.lower().str.replace(" ","_")) #column name modify 
df.head(5)

,transaction_id,customer_id,transaction_date,transaction_time,transaction_amount,payment_method,transaction_status,failure_reason,bank_name,city,device_type,customer_type
0,TXN001,CUST001,2026-07-01,10:30,2500,UPI,Success,NaN,HDFC Bank,Chennai,Android,Existing
1,TXN002,CUST002,01/07/2026,11.15 AM,"₹3,500",upi,SUCCESS,NaN,hdfc bank,chennai,android,existing
2,TXN003,CUST003,2026/07/02,14:20:10,INR 1200,Debit Card,Failed,Insufficient Balance,SBI,Bengaluru,iOS,New
3,TXN004,CUST004,02-07-2026,03:45 PM,"4,800",debit card,failed,insufficient balance,sbi,Bangalore,IOS,new
4,TXN005,CUST005,03-Jul-2026,09.10.30,7000,Credit Card,Pending,NaN,ICICI Bank,Mumbai,Web,Existing

In [6]:
#check the null and negelect the null values 
df.isnull().sum()
df=df.dropna(subset =["customer_id","transaction_date","transaction_time","payment_method","bank_name","city"])
df.isnull().sum()

transaction_id         0
customer_id            0
transaction_date       0
transaction_time       0
transaction_amount     0
payment_method         0
transaction_status     0
failure_reason        29
bank_name              0
city                   0
device_type            0
customer_type          0
dtype: int64

In [7]:
#check ths duplicates
for col in df.columns:
    print(col, df[col].duplicated().sum())

transaction_id 1
customer_id 1
transaction_date 1
transaction_time 1
transaction_amount 3
payment_method 33
transaction_status 37
failure_reason 34
bank_name 32
city 32
device_type 38
customer_type 40

In [8]:
#drop the duplicates values
df.drop_duplicates(subset=["transaction_id","customer_id"],inplace=True) #while assigning don't use the inplace it will show error 
for col in df.columns:
    print(col, df[col].duplicated().sum())

transaction_id 0
customer_id 0
transaction_date 0
transaction_time 0
transaction_amount 2
payment_method 32
transaction_status 36
failure_reason 33
bank_name 31
city 31
device_type 37
customer_type 39

In [9]:
#remove the space in data of all the column
for col in df.select_dtypes(include=["object","number"]).columns:
   df[col]=df[col].str.strip().str.title()

df.head(5)

,transaction_id,customer_id,transaction_date,transaction_time,transaction_amount,payment_method,transaction_status,failure_reason,bank_name,city,device_type,customer_type
0,Txn001,Cust001,2026-07-01,10:30,2500,Upi,Success,NaN,Hdfc Bank,Chennai,Android,Existing
1,Txn002,Cust002,01/07/2026,11.15 Am,"₹3,500",Upi,Success,NaN,Hdfc Bank,Chennai,Android,Existing
2,Txn003,Cust003,2026/07/02,14:20:10,Inr 1200,Debit Card,Failed,Insufficient Balance,Sbi,Bengaluru,Ios,New
3,Txn004,Cust004,02-07-2026,03:45 Pm,"4,800",Debit Card,Failed,Insufficient Balance,Sbi,Bangalore,Ios,New
4,Txn005,Cust005,03-Jul-2026,09.10.30,7000,Credit Card,Pending,NaN,Icici Bank,Mumbai,Web,Existing

In [10]:
#cleaning transaction amount
df["transaction_amount"]=(df["transaction_amount"].str.replace("₹","").
                          str.replace(",","").
                          str.replace("Inr","").
                          str.strip())

In [11]:
df["transaction_amount"]=pd.to_numeric(df["transaction_amount"],errors="coerce")
df.info()
df=df[df["transaction_amount"]>0]
df.head(5)

<class 'pandas.core.frame.DataFrame'>
Index: 44 entries, 0 to 49
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   transaction_id      44 non-null     object
 1   customer_id         44 non-null     object
 2   transaction_date    44 non-null     object
 3   transaction_time    44 non-null     object
 4   transaction_amount  44 non-null     int64
 5   payment_method      44 non-null     object
 6   transaction_status  44 non-null     object
 7   failure_reason      16 non-null     object
 8   bank_name           44 non-null     object
 9   city                44 non-null     object
 10  device_type         44 non-null     object
 11  customer_type       44 non-null     object
dtypes: int64(1), object(11)
memory usage: 4.5+ KB

,transaction_id,customer_id,transaction_date,transaction_time,transaction_amount,payment_method,transaction_status,failure_reason,bank_name,city,device_type,customer_type
0,Txn001,Cust001,2026-07-01,10:30,2500,Upi,Success,NaN,Hdfc Bank,Chennai,Android,Existing
1,Txn002,Cust002,01/07/2026,11.15 Am,3500,Upi,Success,NaN,Hdfc Bank,Chennai,Android,Existing
2,Txn003,Cust003,2026/07/02,14:20:10,1200,Debit Card,Failed,Insufficient Balance,Sbi,Bengaluru,Ios,New
3,Txn004,Cust004,02-07-2026,03:45 Pm,4800,Debit Card,Failed,Insufficient Balance,Sbi,Bangalore,Ios,New
4,Txn005,Cust005,03-Jul-2026,09.10.30,7000,Credit Card,Pending,NaN,Icici Bank,Mumbai,Web,Existing

In [12]:
#cleaning date format
df["transaction_date"]=pd.to_datetime(df["transaction_date"],errors="coerce",dayfirst=True,format="mixed")
df = df.dropna(subset=["transaction_date"])
df.head(5)

,transaction_id,customer_id,transaction_date,transaction_time,transaction_amount,payment_method,transaction_status,failure_reason,bank_name,city,device_type,customer_type
0,Txn001,Cust001,2026-07-01,10:30,2500,Upi,Success,NaN,Hdfc Bank,Chennai,Android,Existing
1,Txn002,Cust002,2026-07-01,11.15 Am,3500,Upi,Success,NaN,Hdfc Bank,Chennai,Android,Existing
2,Txn003,Cust003,2026-07-02,14:20:10,1200,Debit Card,Failed,Insufficient Balance,Sbi,Bengaluru,Ios,New
3,Txn004,Cust004,2026-07-02,03:45 Pm,4800,Debit Card,Failed,Insufficient Balance,Sbi,Bangalore,Ios,New
4,Txn005,Cust005,2026-07-03,09.10.30,7000,Credit Card,Pending,NaN,Icici Bank,Mumbai,Web,Existing

In [13]:
#cleaning time format
df["transaction_time"]=(pd.to_datetime(df["transaction_time"].str.replace(".",":"),errors="coerce",format="mixed")).dt.strftime("%H:%M")
df["transaction_time"].isnull().sum()
df.head(5)

,transaction_id,customer_id,transaction_date,transaction_time,transaction_amount,payment_method,transaction_status,failure_reason,bank_name,city,device_type,customer_type
0,Txn001,Cust001,2026-07-01,10:30,2500,Upi,Success,NaN,Hdfc Bank,Chennai,Android,Existing
1,Txn002,Cust002,2026-07-01,11:15,3500,Upi,Success,NaN,Hdfc Bank,Chennai,Android,Existing
2,Txn003,Cust003,2026-07-02,14:20,1200,Debit Card,Failed,Insufficient Balance,Sbi,Bengaluru,Ios,New
3,Txn004,Cust004,2026-07-02,15:45,4800,Debit Card,Failed,Insufficient Balance,Sbi,Bangalore,Ios,New
4,Txn005,Cust005,2026-07-03,09:10,7000,Credit Card,Pending,NaN,Icici Bank,Mumbai,Web,Existing

In [ ]:
# I need to merge the twocolumns

In [14]:
df["transaction_datetime"]=df["transaction_date"].astype(str).str.strip()+" " +df["transaction_time"].astype(str).str.strip()
df.drop(columns=["transaction_date","transaction_time"], inplace=True)
df.head(5)

,transaction_id,customer_id,transaction_amount,payment_method,transaction_status,failure_reason,bank_name,city,device_type,customer_type,transaction_datetime
0,Txn001,Cust001,2500,Upi,Success,NaN,Hdfc Bank,Chennai,Android,Existing,2026-07-01 10:30
1,Txn002,Cust002,3500,Upi,Success,NaN,Hdfc Bank,Chennai,Android,Existing,2026-07-01 11:15
2,Txn003,Cust003,1200,Debit Card,Failed,Insufficient Balance,Sbi,Bengaluru,Ios,New,2026-07-02 14:20
3,Txn004,Cust004,4800,Debit Card,Failed,Insufficient Balance,Sbi,Bangalore,Ios,New,2026-07-02 15:45
4,Txn005,Cust005,7000,Credit Card,Pending,NaN,Icici Bank,Mumbai,Web,Existing,2026-07-03 09:10

In [15]:
df.insert(
    2,
    "transaction_datetime",
    df.pop("transaction_datetime")
)

In [16]:
df.head(5)

,transaction_id,customer_id,transaction_datetime,transaction_amount,payment_method,transaction_status,failure_reason,bank_name,city,device_type,customer_type
0,Txn001,Cust001,2026-07-01 10:30,2500,Upi,Success,NaN,Hdfc Bank,Chennai,Android,Existing
1,Txn002,Cust002,2026-07-01 11:15,3500,Upi,Success,NaN,Hdfc Bank,Chennai,Android,Existing
2,Txn003,Cust003,2026-07-02 14:20,1200,Debit Card,Failed,Insufficient Balance,Sbi,Bengaluru,Ios,New
3,Txn004,Cust004,2026-07-02 15:45,4800,Debit Card,Failed,Insufficient Balance,Sbi,Bangalore,Ios,New
4,Txn005,Cust005,2026-07-03 09:10,7000,Credit Card,Pending,NaN,Icici Bank,Mumbai,Web,Existing

In [17]:
#replace the value in the payment methods

changing={
    "Cc":"Credit Card",
    "CreditCard":"Credit Card",
    "Debitcard":"Debit Card",
    "Upi":"UPI",
    "Netbanking":"Net Banking",
    "Wallet":"Wallet"
}

df["payment_method"]=df["payment_method"].replace(changing)  # we can use map and replace if you give all he value replace go with map some value changing go with replace 
df.head(5)

,transaction_id,customer_id,transaction_datetime,transaction_amount,payment_method,transaction_status,failure_reason,bank_name,city,device_type,customer_type
0,Txn001,Cust001,2026-07-01 10:30,2500,UPI,Success,NaN,Hdfc Bank,Chennai,Android,Existing
1,Txn002,Cust002,2026-07-01 11:15,3500,UPI,Success,NaN,Hdfc Bank,Chennai,Android,Existing
2,Txn003,Cust003,2026-07-02 14:20,1200,Debit Card,Failed,Insufficient Balance,Sbi,Bengaluru,Ios,New
3,Txn004,Cust004,2026-07-02 15:45,4800,Debit Card,Failed,Insufficient Balance,Sbi,Bangalore,Ios,New
4,Txn005,Cust005,2026-07-03 09:10,7000,Credit Card,Pending,NaN,Icici Bank,Mumbai,Web,Existing

In [18]:
ch={"Sbi":"SBI",
   "Kotak Mahindra Bank":"Kotak Bank"}
df["bank_name"]=df["bank_name"].replace(ch)
df.head(5)

,transaction_id,customer_id,transaction_datetime,transaction_amount,payment_method,transaction_status,failure_reason,bank_name,city,device_type,customer_type
0,Txn001,Cust001,2026-07-01 10:30,2500,UPI,Success,NaN,Hdfc Bank,Chennai,Android,Existing
1,Txn002,Cust002,2026-07-01 11:15,3500,UPI,Success,NaN,Hdfc Bank,Chennai,Android,Existing
2,Txn003,Cust003,2026-07-02 14:20,1200,Debit Card,Failed,Insufficient Balance,SBI,Bengaluru,Ios,New
3,Txn004,Cust004,2026-07-02 15:45,4800,Debit Card,Failed,Insufficient Balance,SBI,Bangalore,Ios,New
4,Txn005,Cust005,2026-07-03 09:10,7000,Credit Card,Pending,NaN,Icici Bank,Mumbai,Web,Existing

In [19]:
chi={"Bengaluru":"Bangalore"}
df["city"]=df["city"].replace(chi)
df.head(5)

,transaction_id,customer_id,transaction_datetime,transaction_amount,payment_method,transaction_status,failure_reason,bank_name,city,device_type,customer_type
0,Txn001,Cust001,2026-07-01 10:30,2500,UPI,Success,NaN,Hdfc Bank,Chennai,Android,Existing
1,Txn002,Cust002,2026-07-01 11:15,3500,UPI,Success,NaN,Hdfc Bank,Chennai,Android,Existing
2,Txn003,Cust003,2026-07-02 14:20,1200,Debit Card,Failed,Insufficient Balance,SBI,Bangalore,Ios,New
3,Txn004,Cust004,2026-07-02 15:45,4800,Debit Card,Failed,Insufficient Balance,SBI,Bangalore,Ios,New
4,Txn005,Cust005,2026-07-03 09:10,7000,Credit Card,Pending,NaN,Icici Bank,Mumbai,Web,Existing

In [20]:
wn={"Ios":"IOS"}
df["device_type"]=df["device_type"].replace(wn)

df.head(5)

,transaction_id,customer_id,transaction_datetime,transaction_amount,payment_method,transaction_status,failure_reason,bank_name,city,device_type,customer_type
0,Txn001,Cust001,2026-07-01 10:30,2500,UPI,Success,NaN,Hdfc Bank,Chennai,Android,Existing
1,Txn002,Cust002,2026-07-01 11:15,3500,UPI,Success,NaN,Hdfc Bank,Chennai,Android,Existing
2,Txn003,Cust003,2026-07-02 14:20,1200,Debit Card,Failed,Insufficient Balance,SBI,Bangalore,IOS,New
3,Txn004,Cust004,2026-07-02 15:45,4800,Debit Card,Failed,Insufficient Balance,SBI,Bangalore,IOS,New
4,Txn005,Cust005,2026-07-03 09:10,7000,Credit Card,Pending,NaN,Icici Bank,Mumbai,Web,Existing

In [24]:
df["failure_reason"]=df["failure_reason"].fillna("Unknown")

In [21]:
df.head(5)

,transaction_id,customer_id,transaction_datetime,transaction_amount,payment_method,transaction_status,failure_reason,bank_name,city,device_type,customer_type
0,Txn001,Cust001,2026-07-01 10:30,2500,UPI,Success,NaN,Hdfc Bank,Chennai,Android,Existing
1,Txn002,Cust002,2026-07-01 11:15,3500,UPI,Success,NaN,Hdfc Bank,Chennai,Android,Existing
2,Txn003,Cust003,2026-07-02 14:20,1200,Debit Card,Failed,Insufficient Balance,SBI,Bangalore,IOS,New
3,Txn004,Cust004,2026-07-02 15:45,4800,Debit Card,Failed,Insufficient Balance,SBI,Bangalore,IOS,New
4,Txn005,Cust005,2026-07-03 09:10,7000,Credit Card,Pending,NaN,Icici Bank,Mumbai,Web,Existing

In [26]:
df.to_excel("final.xlsx",index=False) # excel save

In [140]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\viicky crackerspot\anaconda3\lib\site-packages (2.0.43)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet>=1 in c:\users\viicky crackerspot\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\viicky crackerspot\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [144]:
from sqlalchemy import create_engine
#step connect mysql
username="root"
password="root"
host="localhost"
port="3306"
database="fintech_project"

engine=create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

#step2 load the table
tablename="customer_transactions"
df.to_sql(tablename,engine,if_exists="replace",index=False)

print(f"data has been successfully loaded into the table  '{tablename}' in database '{database}'")

data has been successfully loaded into the table  'customer_transactions' in database 'fintech_project'